name: Context Demo

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Analysis:
        name: Erste Analyse
        runs-on: ubuntu-latest
        env:
            GEHEIM: ${{ secrets.MY_SECRET }}

        steps:
            - name: Zeige unser Geheimnis
              run: echo $GEHEIM

            - name: Zeige GitHub Kontext
              run: echo '${{ toJson(github) }}'

            - name: Zeige Steps Kontext
              run: echo '${{ toJson(steps) }}'

            - name: Zeige Runner Kontext
              run: echo '${{ toJson(runner) }}'