# Workflow konfiguration
name: Hello World
description: Das ist nur ein Hello World Beispiel
env:
  GLOBAL_MESSAGE: "Hallo aus dem Workflow"

# Events
on: 
    push:
        branches:
            - main
            - 'features/**'
            - '!features/old'
    workflow_dispatch: 

# Jobs
jobs:
    say-hello:
        runs-on: ubuntu-latest
        env:
            JOB_MESSAGE: "Hallo aus dem Job"

        steps:
            - name: Ausgabe global und Job
              run: |
                echo "GLOBAL_MESSAGE: $GLOBAL_MESSAGE"
                echo "JOB_MESSAGE: $JOB_MESSAGE"

            - name: Aktuelles Verzeichnis ansehen
              env:
                STEP_MESSAGE: 'Message aus dem Step'
              run: pwd && ls -al && echo $STEP_MESSAGE

            - name: Checkout der Dateien
              uses: actions/checkout@v4
              
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al && echo $STEP_MESSAGE

            - name: Lade hello-world.js als Artifact hoch
              uses: actions/upload-artifact@v4
              with:
                name: hello-world.js datei
                path: hello-world.js

    say-bye:
        runs-on: ubuntu-latest
        needs: say-hello

        steps:
            - name: Ausgabe global und Job
              run: |
                echo "GLOBAL_MESSAGE: $GLOBAL_MESSAGE"
                echo "JOB_MESSAGE: $JOB_MESSAGE"

            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Lade hello-world.js von Artifact herunter
              uses: actions/download-artifact@v4
              with:
                name: hello-world.js datei

            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Nodejs ausführen
              run: node hello-world.js

            - name: Abschied
              run: echo "Bye bye"