# Workflow konfiguration
name: Hello World
description: Das ist nur ein Hello World Beispiel

# Events
on: 
    push:
        branches:
            - main
            - 'features/**'
            - '!features/old'
    workflow_dispatch: 

# Jobs
jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Checkout der Dateien
              uses: actions/checkout@v4
              
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Lade hello-world.js als Artifact hoch
              uses: actions/upload-artifact@v4
              with:
                name: hello-world.js datei
                path: hello-world.js

    say-bye:
        runs-on: ubuntu-latest
        needs: say-hello

        steps:
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Lade hello-world.js von Artifact herunter
              uses: actions/download-artifact@v4
              with:
                name: hello-world.js datei

            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Nodejs ausführen
              run: node hello-world.js

            - name: Abschied
              run: echo "Bye bye"